### ISSUE TITLE
Audit Log messages

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/aktualizr#102]
At the moment the log output is rather 'chatty'. We should check the levels of all the log messages, and standardise them. Here are some example guidelines:

- Trace: Verbose debugging messages. May generate high volumes of messages, and they are designed to be read in conjunction with the source code by a developer
- Debug: Much lower volume than Trace, but still designed to be read in conjunction with the source code. Debug messages should not contain security-sensitive information, because they will often be requested from the customer.
- Info messages are for users to debug problems and understand the operation of the software. They should make sense without the source code
- Warning messages should be used when something is likely wrong or incorrect, but the program can continue working correctly. If nothing is wrong, then the Info level should be used instead.
- Error messages are for errors where the system has failed to operate to specification in some way.

Thus:
- The general 'chat' at startup (including version number and build) should be at the 'Info' level
- Display of the actual configuration settings (including secrets) should be only at the trace level
- The normal polling loop should only output a single message at the 'Info' level, but possibly multiple 'Debug' level messages.
- TCP time-outs should generate Warning level messages
- 500 or  403 errors from the server should generate Error level messages

**Comment by jeremiah** [comment]
Are there plans to use GENIVI's DLT for logging? This is the standard logging mechanism for ECUs and IVI systems and specified by AUTOSAR and GENIVI.

**Comment by cajun-rat** [comment]
Hi @jeremiah We've talked about it in #13, but haven't made an attempt at an implementation yet. Our default deployment scenario is a systemd service, so I would prefer that any improved logging support didn't interfere with the normal systemd commands like 'systemd status'.

**Comment by jeremiah** [comment]
Your approach makes sense. Having aktualizr connect the journal to DLT on the client side is maybe useful too, I understand a lot of companies do that.

**Comment by gunnarx** [comment]
For C++ programs we now recommend the [ivi-logging](https://github.com/Pelagicore/ivi-logging) interface to get a nice C++ style interface and multiple potential backends.  The recipe for including it is now in meta-genivi-dev. (Could be moved to any other layer on request).

It might have the benefit of:
 - A "shared" definition of levels
 - A subclass that implements a DLT backend exists
 - Not sure if a pure systemd journal backend exists yet but it should be trivial to do.  Alternatively systemd would pick up console logging (which is supported) would it not?
