### ISSUE TITLE
How To run Aktualizer package in Eclipse IDE?

### ISSUE THREAD

**Issue by koruthu** [advancedtelematic/aktualizr#1069]
Following are the issues(question) i am facing during build process:
> How to use Boost and Tests package without doing any changes in terms of path which has relation with #include<> and # include" " ?(We are facing major errors with this include files as it is cascading with lots of files)

>How to disable the **test** folder while building the project,  which is present inside the folder Boost, crypto, storage... etc. 

>What are the steps to  run Aktualizer package in Eclipse IDE?
> We are using the "master" for build and running but is it stable codes? as we are not able to build it at all, If this is not the correct release , please point us towards the correct rlease which may run in Eclipse IDE.
  
>Is there any documentation available explaining the structure and how to use this Package?

**Comment by patrickvacek** [comment]
Hello @koruthu,

**Comment by OYTIS** [comment]
Hi @koruthu 

> How to use Boost and Tests package without doing any changes in terms of path which has relation with #include<> and # include" " ?(We are facing major errors with this include files as it is cascading with lots of files)

Sorry to hear that. Could you attach some logs/more detailed description of the problems you're having?

> How to disable the test folder while building the project, which is present inside the folder Boost, crypto, storage... etc

Tests are only built when you're building the `build_tests` make target.

> What are the steps to run Aktualizer package in Eclipse IDE?
> We are using the "master" for build and running but is it stable codes? as we are not able to build it at all, If this is not the correct release , please point us towards the correct rlease which may run in Eclipse IDE.

The master branch should be stable, that's our goal. The version that's in the current `meta-updater` master (https://github.com/advancedtelematic/meta-updater/blob/master/recipes-sota/aktualizr/aktualizr_git.bb) undergoes a bit more thorough testing, so you can use that to be on a safe side.
Again, we would be grateful for the logs.

> Is there any documentation available explaining the structure and how to use this Package?

For basic building instructions you can address to README. There are more detailed docs in the `docs` directory. Finally, for [meta-updater](https://github.com/advancedtelematic/meta-updater) layer there are step-by-step instructions in case you want to use Aktualizr with Yocto: this is the most user-friendly scenario.

**Comment by koruthu** [comment]
Hi @OYTIS 

[FOTA_Uptane.build.log](https://github.com/advancedtelematic/aktualizr/files/2794920/FOTA_Uptane.build.log)

Thanks a lot for your answers,
Please find the attached log, which was generated when we tried to build the package in eclipse IDE.

Also we would like to  know if this package would work on windows? or linux system is required?

We have gone through read me files, and followed the steps accordingly but issues are the same.

Kindly let me know if you require any more information regarding the same.

**Comment by patriotyk** [comment]
Looks like your environment doesn't see the make utility. Also I noticed that you build it in the Windows OS, which is not supported.

**Comment by koruthu** [comment]
Hi @patriotyk ,
Thanks for your answer,
So in Linux system do we need to install  any other packages, tools or listed dependencies  (like boost, openssl etc) in order to run Aktualizer?

**Comment by patrickvacek** [comment]
> What are the steps to run Aktualizer package in Eclipse IDE?

Unfortunately we have no experience with building aktualizr with Eclipse or on Windows. Using Eclipse on Linux should be possible with some configuration work, but if you have cmake and make or ninja, it is reasonably easy to build on the command line. Supporting Windows is unlikely. Our target environment is normally embedded Linux, but we have some experience with running aktualizr on Linux and Mac desktops for testing and demonstration purposes.

> do we need to install any other packages, tools or listed dependencies

aktualizr's dependencies are listed in the [README](https://github.com/advancedtelematic/aktualizr#dependencies).

**Comment by doanac** [comment]
This isn't exactly what you want, but I've found the easiest way for me to build for x86 is to use Docker with: 
 https://github.com/advancedtelematic/aktualizr/blob/master/docker/Dockerfile.ubuntu.bionic

That's got enough stuff in it to build, make a fake ostree and do some work. Once I get past the re-compile/debug stage, I then use OE to build my copy of aktualizr for my target device.

**Comment by OYTIS** [comment]
@patriotyk @koruthu I believe the problem is rather that Eclipse is trying to build is as a `make` project, while in reality it uses `cmake`. I also don't have any experience with using Eclipse with cmake, but quick googling shows that is possible.

**Comment by koruthu** [comment]
Hi,

Thanks for the answers @OYTIS @doanac @patriotyk @patrickvacek 

[terminal Log.txt](https://github.com/advancedtelematic/aktualizr/files/2806740/terminal.Log.txt)

Now i am trying to run this in Genivi development platform via virtual machine. the issue i am facing is the with boost and sodium libraries. i have both the packages but its not able to locate or identify respective library's location. 
Is there any special location or path where i have to add the boost and sodium files? 

Please find the attached logs.

**Comment by patrickvacek** [comment]
@koruthu It looks like you are trying to build the SDK via the steps in https://github.com/advancedtelematic/aktualizr/#developing-and-debugging-with-an-openembedded-system. Is that correct? If so, I think you may have unfortunately stumbled upon a bug that cropped up a while ago that we haven't figured out how to address. We admittedly do not have need to use the SDK very often. What are you trying to accomplish with the SDK? Or if I've entirely misunderstood, please explain what you are trying to build.

**Comment by koruthu** [comment]
@patrickvacek Yes I am following the same instructions mentioned below these codes. 
We want to build the aktualizr package create binaries and executable files which would be useful for creating a OTA client in raspberry pi 3 system. 
So with GDP- SDK (which is compatible with raspberry pi 3)   we want to replicate the OTA system with aktaulizr and server portion of the OTA (which we have yet to build).

**Comment by patrickvacek** [comment]
@koruthu The primary way we build aktualizr is via the [meta-updater](https://github.com/advancedtelematic/meta-updater/) layer in Yocto. We actively maintain that and use it as part of our core product. Raspberry Pis are a supported target and we use them often. I believe GENIVI also uses Yocto, so integrating meta-updater into your project will hopefully not be a big chore. We have a [basic repo](https://github.com/advancedtelematic/updater-repo/) set up for getting started that might serve as an example, or you may want to read our [official docs](https://docs.ota.here.com/).

The other way we build aktualizr is on our desktop computers, although that is only suitable for development and testing purposes. We have only ever used the SDK for development and debugging purposes, as noted in the README, and unfortunately it has been a long time since anyone has tried using that, as it is rarely very useful. If you are intending to create a standard workflow for building aktualizr, meta-updater is a much more reliable method.

**Comment by koruthu** [comment]
Hello all,
we are still struggling to build Aktualizr we are usiing doocker poky containers. log attached 
[20190205093518.log](https://github.com/advancedtelematic/aktualizr/files/2835638/20190205093518.log)

We are following according to the documentations and even built(which takes many hours) this, but we cant find any  Executable file or any means to see the output/test the aktualizr. Kindly give us some steps to get this up and running. let us know if more information required regarding the same.
Thanks .

**Comment by patrickvacek** [comment]
Is this related to https://github.com/advancedtelematic/meta-updater/issues/475?

At any rate, it looks like your bitbake log attached here was successful. Unfortunately bitbaking the first time does take many hours; that is an unfortunate reality of building your own OS from scratch. You should find the output image in `<build-dir>/tmp/deploy/images/<machine-name>/`. It looks like you built for qemu. We have a convenience script in meta-updater for running qemu images. See [`scripts/run-qemu-ota`](https://github.com/advancedtelematic/meta-updater/blob/master/scripts/run-qemu-ota).

**Comment by patrickvacek** [comment]
Closing due to lack of response and clarity.
