### ISSUE TITLE
Uptane logic not compatible with theupdateframework/notary

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1073]
I don't know enough about the TUF spec to know what the correct behavior or expectations should be, but I noticed something interesting today. I've set up a Docker Notary server to hold my OSTree hashes and found aktualizr was unable to process the timestamps.json file. Here's the good part of the log:
~~~
> GET /tuf/v2/hub.foundries.io/lmp/_trust/tuf/timestamp.json HTTP/1.1
...
response http code: 200
response: {"signed":{"_type":"Timestamp","expires":"2019-02-11T22:29:03.747270126Z","meta":{"snapshot":{"hashes":{"sha256":"zPv6f+Q5qhJHBm3+0FkjAJXrapW2dxDM3T2l/626QVk=","sha512":"+fEiNyEeGbPEK3MquCStmsFmtzafI9XIK1TAomAXUYvsxjmKYHN6GVFD0bogYO65sgQlijttWkbBUJFqd2egNA=="},"length":683}},"version":2},"signatures":[{"keyid":"e1751558728e25b0bfb35250bac5ed1b776689684258b8b8405057bf42f29278","method":"ecdsa","sig":"gyqM9wgCQU78WWHg/AxxPblCAjnmXP383G0wKKc4J7riMNTtGz9YHQK4e+2cTnF7iERA4Gyae10/UOv7wRAHlQ=="}]}
~~~

Looking [here](https://github.com/advancedtelematic/aktualizr/blob/master/src/libaktualizr/uptane/tuf.cc#L288) it appears things are hard-coded to expect `targets.json` instead of `targets`. It also looks like the logic for dealing with snapshot.json will have the same issue.

Not sure if this is a bug or an acceptable implementation detail? I guess a "fix" might be something like:
~~~
const char *key = "snapshot.json"
if (!json["signed"]["meta"][key].isObject)
  key = "snapshot.json";
Json::Value hashes_list = json["signed"]["meta"][key]["hashes"];
...
~~~

**Comment by patrickvacek** [comment]
In the [TUF spec](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats), the example uses the versions with `.json`. I don't think that is specifically required (the use of JSON itself is not a requirement), but we've kept fairly true to the example formats for simplicity. Is it possible to configure Docker Notary, or is that just how it works? Unfortunately TUF implementations are not guaranteed to be interoperable.

**Comment by OYTIS** [comment]
Looks like a bug in Docker Notary to me. TUF specifies that `snapshot.json` has `METAPATH` there, where `METAPATH` "is the the metadata file's path on the repository relative to the metadata base URL". So if the file is served from the server as `targets.json`, it should be called like that in `snapshot.json`.

**Comment by doanac** [comment]
thanks for the feedback. I've raised the issue in Notary and it looks like they are looking into a fix.
