### ISSUE TITLE
SOTA client Architecture

### ISSUE THREAD

**Issue by koruthu** [advancedtelematic/aktualizr#1095]
Is there a architecture diagram or detail documentations regarding working of SOTA client (Aktualizr)?
We are focused on the use of uptane in this package, but it is totally different from studying uptane as single(separate) package. So we would like to find the link. hence we require the architecture/ or any related documentations.  

Also after building this software package what will be the output(s) and interface? What would be final build results.

**Comment by merltron** [comment]
Hi @koruthu, does the content in the docs folder not have what you're looking for? https://github.com/advancedtelematic/aktualizr/tree/master/docs
There are some fairy detailed descriptions of aktualizr's interactions in there

**Comment by patrickvacek** [comment]
> We are focused on the use of uptane in this package, but it is totally different from studying uptane as single(separate) package.

libaktualizr is an Uptane-compliant client, but it is specifically intended to work with our HERE OTA Connect backend, so it also does a lot of things specific to that. Interoperability is ideal, but there hasn't been much impetus to make it a reality until quite recently.

> Also after building this software package what will be the output(s) and interface? What would be final build results.

If you follow the build instructions in the README, you can find the compiled executables in the build tree. For example, `aktualizr` will be in `<build-dir>/src/aktualizr_primary/aktualizr`. You can run `make install` if you want to install everything on your local machine, although I don't normally recommend running aktualizr on a host system except for testing. You can also run `make package` to produce debian packages.

**Comment by zabbal** [comment]
Note: #1193 is potentially related related.

**Comment by patrickvacek** [comment]
Closing due to lack of response.
