### ISSUE TITLE
unbound variable DOCKER_OPTS[@] when running scripts/run_docker_test.sh

### ISSUE THREAD

**Issue by bclouser** [advancedtelematic/aktualizr#1124]
Am I the only one seeing this error?

`./scripts/run_docker_test.sh: line 49: DOCKER_OPTS[@]: unbound variable`

**Comment by patrickvacek** [comment]
> Am I the only one seeing this error?

Possibly. I've never seen it. Thank you for the PR, though! I'll take a look soon.

**Comment by patrickvacek** [comment]
Closing because this is fixed.
