### ISSUE TITLE
credentials.zip description is unclear/outdated

### ISSUE THREAD

**Issue by zabbal** [advancedtelematic/aktualizr#1193]
According to https://github.com/advancedtelematic/aktualizr/blob/master/docs/credentials.adoc the credentials.zip should contain client.crt, client.key and root.crt among other things. Those are missing from the .zip I've just obtained. So either the description got out of sync or there's note missing to clarify which files are optional and why/when this happens.

**Comment by patrickvacek** [comment]
The language there does not make that clear, but those three components are actually part of `autoprov_credentials.p12`.

**Comment by patrickvacek** [comment]
The doc has since been updated (and moved to https://github.com/advancedtelematic/aktualizr/blob/master/docs/ota-client-guide/modules/ROOT/pages/provisioning-methods-and-credentialszip.adoc). This got fixed somewhere along the way.
