### ISSUE TITLE
Get rid of pre*/postinst hacks in .deb packages

### ISSUE THREAD

**Issue by zabbal** [advancedtelematic/aktualizr#1227]
Right now we call systemctl directly in aktualizr/config/systemd/debian-control - this makes lintian unhappy and looks rather hacky. We should update it to do the right thing using deb-systemd-helper - see https://lintian.debian.org/tags/maintainer-script-calls-systemctl.html for details.

**Comment by lbonn** [comment]
Was done in #1242
