### ISSUE TITLE
Support automatic provisioning using mutual TLS 

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/aktualizr#123]
See docs/automatic-provisioning.adoc (currently in the docs/automatic-provision branch)

**Comment by cajun-rat** [comment]
There is an example of the https requests that are needed for automatic provisioning here: https://github.com/advancedtelematic/rvi_sota_client/blob/master/run/sota_prov.sh

**Comment by codders** [comment]
Incidentally, that file contains a #FIXME without a JIRA reference. Would be great if that could be fixed.

**Comment by cajun-rat** [comment]
Done
