### ISSUE TITLE
How to increase testing of code paths using OstreeManager::getCurrent

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1256]
There are a couple of things I've been looking at doing recently in aktualizr-lite to help increase test coverage. One problem I'm having is where code paths run through `OstreeManager::getCurrent`. The current logic requires an actual booted deployment:
~~~
Uptane::Target OstreeManager::getCurrent() const {
  GObjectUniquePtr<OstreeSysroot> sysroot_smart = OstreeManager::LoadSysroot(config.sysroot);
  OstreeDeployment *booted_deployment = ostree_sysroot_get_booted_deployment(sysroot_smart.get());
  if (booted_deployment == nullptr) {
    throw std::runtime_error("Could not get booted deployment in " + config.sysroot.string());
  }
...
~~~

I'm not an ostree expert and haven't really seen a way that we could fake this in CI. Hopefully I'm wrong and there's something simple we could add to the makephysical.sh script. However, if this really isn't something we can fake, then I was wondering if you guys had thoughts/opinions on how we could get unit tests to call this function without throwing an exception.

One idea I had was adding a private method like `setFakeCurrent(Uptane::Target t)`. Then you could check `if (booted_deployment == nullptr && !fakeCurrent_)...`. Then code wanting to use this could add "FRIEND_TEST" entries into the class. You could also just check an environment variable or config value at runtime. The latter approach would allow someone to test an aktualizr-lite binary w/o modification.

I don't have strong opinions. Just hoping to sort out a path forward.

**Comment by lbonn** [comment]
We've had this problem before and decided to not add a flag to be compiled in the released application.

You can have a look at the trick we used:

https://github.com/advancedtelematic/aktualizr/blob/46b2884126bf790f22207fa8d4c5d0585ac349d4/src/libaktualizr/primary/CMakeLists.txt#L21

and here

https://github.com/advancedtelematic/aktualizr/blob/46b2884126bf790f22207fa8d4c5d0585ac349d4/src/libaktualizr/primary/aktualizr_fullostree_test.cc

It's quite hacky arguably and relies on dynamic linking, also the test case itself seems to be quite dependent on the OStree version it was developed against.
It mostly works though :)

**Comment by doanac** [comment]
I actually like the LD_PRELOAD idea. I thought about suggesting that as well and thought you guys might think I was too crazy :)

Its a good balance for my specific need because I was hoping to be able to test aktualizr-lite exactly as it would be in production.
