### ISSUE TITLE
Integrate support for GENIVI DLT as logging framework option

### ISSUE THREAD

**Issue by codders** [advancedtelematic/aktualizr#13]
Diagnostic Log and Trace is a logging framework used in GENIVI-compliant systems (and other automotive projects). It would be great to add support for DLT as a logger for better integration with those systems:

https://github.com/GENIVI/dlt-daemon

**Comment by gunnarx** [comment]
**ivi-logging** is a good alternative for accessing DLT with a C++ interface (see detailed comment on #102)
