### ISSUE TITLE
Embedded World 2020 - call for papers - submission date 30 Aug

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1324]
Not sure if you guys are interested, but [Embedded World](https://events.weka-fachmedien.de/embedded-world-conference/home.html) is in Germany and might be a good place for us to help try and build up more community interest in aktualizr and OTA Connect. One of their topics of interests is "3.8 Field Updates (OTA)" so I think anything about these projects would be nice.

I'm personally thinking about a submitting a topic along the lines of "aktualizr-lite - the easiest way to add secure updates to your product". It would be a bit similar to what I did at ELC but hopefully with more of a push on "this is the community whee we as an industry need to start collaborating on".

I was wondering if you have already submitted anything or were planning to? If so, maybe I could try and tailor my topic to be more complimentary to what you have planned.

**Comment by tkfu** [comment]
Closing because we submitted something together.
