### ISSUE TITLE
aktualizr-lite unit tests are broken in master

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1350]
I've bisected things down to this commit 0ea8674de387e1ce759c561a8bec78f7e64137be. Its crashing when I call `storage->importData(config.import);`.

I'm looking into a code-fix now. But I'm also wondering how that slipped through CI?

**Comment by doanac** [comment]
n/m - needed to do a clean build of the sqlschema

**Comment by patrickvacek** [comment]
> n/m - needed to do a clean build of the sqlschema

Sorry, another developer was also just burned by this. We thought this worked correctly, but maybe it needs another look.
