### ISSUE TITLE
Using Ninja for the build system

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1369]
Just wondering if you guys have ever considered using Ninja rather than Make for the build system? I've been doing some clean rebuilds today, and tried Ninja instead and it feels much faster. I don't have absolute numbers, but I think it might be worth considering. FYI, I'm using it with:
~~~
mkdir build; cd build
cmake -DBUILD_OSTREE=ON -DBUILD_DOCKERAPP=ON -GNinja ../
ninja
~~~

**Comment by lbonn** [comment]
Most of us indeed use ninja for development as far as I know and bitbake also builds aktualizr with ninja. But we kept using make on CI, maybe for the wrong reasons...

README.adoc also mentions ninja but not in the main instructions, we could actually change that pretty easily.

**Comment by doanac** [comment]
thanks. i see the mention of it now, I must have skimmed past it.

**Comment by lbonn** [comment]
We never changed it mostly. Also, the log output should be a bit less verbose, so I thought it would maybe make some diagnostics more difficult. But that may also be an advantage if we just have to scroll through less lines of useless output.

We can make a try in some PR.

**Comment by lbonn** [comment]
There were actually some real reasons, but we can probably switch: https://github.com/advancedtelematic/aktualizr/pull/1385
