### ISSUE TITLE
Improve log wrapper type checking

### ISSUE THREAD

**Issue by codders** [advancedtelematic/aktualizr#15]
TODO from https://github.com/advancedtelematic/sota_client_cpp/blob/a85e2a0/src/main.cpp#L57-L59

Use the enumeration from the logger.hpp to enable automatic range checking
This requires to overload operators << and >> as shown in the boost header  boost/log/trivial.hpp
Desired result: bpo::value<loggerLevels_t>

**Comment by embmk** [comment]
To do this, the enumeration should be put into a new namespace which also contains prototypes for the << and the >> operator using the enumeration as parameter. The implementation of the overloaded functions for the operators has to be put outside the namespace, preferably in logger.cpp. The functions are used to convert enum members to strings and strings to enum members.
