### ISSUE TITLE
Key Rotation Help

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1552]
I'm trying to figure out the exact procedure to rotate my root key if its an offline key. I see the docs for rotating an online key:

 https://docs.ota.here.com/ota-client/latest/rotating-signing-keys.html

But once I have *that* key, I'm unclear on how to replace it with a new root key. It looks like its going to be something like a:
~~~
 garage-sign root pull
 garage-sign root key add <my new generated root>
 garage-sign root key remove <old offline root key>
 garage-sign root sign
 garage-sign root push
~~~

But I'm sure that's not quite right. I also figure the answer to this issue could result in some new documentation. Thanks,

**Comment by patrickvacek** [comment]
@doanac does the developer documentation for tool at https://github.com/advancedtelematic/ota-tuf/tree/master/cli help answer your question?

**Comment by doanac** [comment]
Thanks. That was enough to give me the confidence to connect the dots. I'm not sure the best way to generically expand that section, but my personal use-case required running these commands:
~~~
# Sanity check
garage-sign root pull --repo ./tufrepo

# Generate new key
keyname="offline-root-$(date +%Y-%m-%d_%H:%M:%S)"
garage-sign key generate --repo ./tufrepo --type rsa --name $keyname
garage-sign root key add --repo ./tufrepo --key-name $keyname

# Remove old key
garage-sign root key remove --repo ./tufrepo --key-id <my old key id i had to look up>

# Sign with both old and new to prove ownership:
garage-sign root sign --repo ./tufrepo  --key-name $keyname --key-name <my offline root keyname I had to look up>

garage-sign root push --repo ./tufrepo
~~~

**Comment by patrickvacek** [comment]
@simao @Raigi do the steps provided here by Andy match your expectations?

**Comment by simao** [comment]
Yes, that makes sense to me.
