### ISSUE TITLE
support Nvidia board like Jestson TX2?

### ISSUE THREAD

**Issue by gengshenghong** [advancedtelematic/aktualizr#1576]
does this ota solution support board like Nvidia Jestson TX2? Is it possible technically?

Thanks,
Shenghong

**Comment by lbonn** [comment]
We have not attempted support for this board but it should be possible.

Using the meta-updater yocto layer is the preferred deployment method for aktualizr. I suggest reading through our documentation on BSP Integration to get started https://docs.ota.here.com/ota-client/latest/bsp-integration.html

In this case, someone released a yocto support for this board here https://github.com/econsystems/meta-jetson-tx2, though it is based on pyro branches and would probably need to be refreshed.

**Comment by lbonn** [comment]
We have not attempted support for this board but it should be possible.

Using the meta-updater yocto layer is the preferred deployment method for aktualizr. I suggest reading through our documentation on BSP Integration to get started https://docs.ota.here.com/ota-client/latest/bsp-integration.html

In this case, someone released a yocto support for this board here https://github.com/econsystems/meta-jetson-tx2, though it is based on pyro branches and would probably need to be refreshed.

**Comment by patrickvacek** [comment]
Closing due to lack of feedback.
