### ISSUE TITLE
fsetxattr: Operation not supported

### ISSUE THREAD

**Issue by eloysu205** [advancedtelematic/aktualizr#1590]
Hi, in our current trying out, we used meta-updater and meta-integrity (IMA stuff) to creat an OTA image. So in the OTA image each file contains an extend attributes named as security.ima. Then we tried to update the file system on rpi, but we got follwoing error message:  
> aktualizr: ostree-pull: Receiving objects: 2%
> aktualizr: ostree-pull: Writing objects: 1
> aktualizr: Error while pulling image: 15 Writing content object: fsetxattr: Operation not supported

Does aktualizr support to update xattr? Or what would occur this error? 
Thanks!

**Comment by patrickvacek** [comment]
This is quite interesting. However, this error is transparently passed to aktualizr from [OSTree](https://github.com/ostreedev/ostree). You might have more luck talking to the OSTree developers.

To my knowledge, nothing about aktualizr itself should restrict `fsetxattr`. @zabbal do you have any additional insight here?

**Comment by eloysu205** [comment]
Thanks for the reply. I just find out the mistake i have made, that I didn't enable
> CONFIG_EXT4_FS_SECURITY=y

Problem is solved and i close this issue.
Thanks again.
