### ISSUE TITLE
Read device ID

### ISSUE THREAD

**Issue by michael-p** [advancedtelematic/aktualizr#1630]
Dear all,

is there a (simple) way to read the device ID on the device itself? If I understand things correctly the device Id is stored in the device certificates, so in theory on could try to locate these certificates on the device and read out the name but I wonder if there is a simpler and stabler way to do this with the aktualizr application on the device?

For completeness, we're running version `1.0+gitAUTOINC+3c1c77c005` of the client.

Best
Michael

**Comment by patrickvacek** [comment]
> is there a (simple) way to read the device ID on the device itself?

Yes, try running `aktualizr-info` on the device. :)

> If I understand things correctly the device Id is stored in the device certificates, so in theory on could try to locate these certificates on the device and read out the name but I wonder if there is a simpler and stabler way to do this with the aktualizr application on the device?

We now do this as well; see https://github.com/advancedtelematic/aktualizr/pull/1555.

> For completeness, we're running version `1.0+gitAUTOINC+3c1c77c005` of the client.

That's a really old version. Please upgrade! Why do you need to use that version?

**Comment by michael-p** [comment]
> Yes, try running aktualizr-info on the device. :)

Oh wow, that was easy! Thank you very much for the super-fast help! :)

> That's a really old version. Please upgrade! Why do you need to use that version?

No real reason for this except that the whole Yocto-build was set up roughly 2 years ago by an engineer who's no longer working on the project and since the device is still in a private beta phase and "it works", no-one updated it. I'll try to push this so that we upgrade as soon as possible, thanks for the heads-up!
