### ISSUE TITLE
Option to control 'sysroot' passed to OSTree

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/aktualizr#164]
By default OSTree operations work against the '/ostree' directory, which is correct for normal operation. For testing it would be useful to be able to:

* Run aktualizr on a normal desktop development system without using Docker or qemu
* Run multiple copies of aktualizr on a single machine for performance/load testing

The ostree command line tools already have a '--sysroot' option that controls this.  This ticket is about adding a similar option to aktualizr that would pass the parameter through to libostree.

For example:

```
ostree admin os-init --sysroot=/home/me/foo myos
sudo ostree pull-local --repo /home/me/foo/ostree/repo/ $REPO commit1
sudo ostree admin deploy --sysroot=/home/me/foo commit1 --os=myos

ostree admin status --sysroot=/home/me/foo
  bob 6fc24bdd09d7865f60b3361f0650887d3f6a5eaaba2a79d6cc1f808347fe43eb.0
    origin refspec: bosch1
aktualizr --sysroot /home/me/foo --config myconfig.toml
```

cc @koshelev

**Comment by cajun-rat** [comment]
@patriotyk makes a good point that we need access to the 'currently booted' commit in order to report the current state of the system to the server.  We will need to fake the value for 'currently booted' commit when run in --sysroot mode.  This should probabily be the last deployed commit

**Comment by OYTIS** [comment]
Solved by https://github.com/advancedtelematic/aktualizr/pull/192
