### ISSUE TITLE
root role disappeared?

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#1646]
I had a device mysteriously stop pulling down metadata from my OTA server today. Of course "nothing has changed". I'm frantically trying to understand how this could happen and what my path to recovery is. The message from aktualizr is:
~~~
 debug: GET https://ota-lite.foundries.io:8443/repo/4.root.json

...

> GET /repo/4.root.json HTTP/1.1
...

< HTTP/1.1 424 Failed Dependency
...
< x-ats-version: reposerver/0.6.0-19-ge074093
< 
* Connection #0 to host ota-lite.foundries.io left intact
  trace: response http code: 424
  trace: response: {"code":"root_role_not_found","description":"root role was not found in upstream key store","cause":null,"errorId":"8e7ecd35-14d3-41f0-a458-252ad1d4a872"}
warning: Unable to update latest metadata, using local copy
~~~

I tried to run some garage sign commands to see if that would somehow fix things. It basically gives the same type of error:
~~~
com.advancedtelematic.libtuf.http.SHttpjServiceClient$HttpjClientError: ReposerverHttpClient|GET|http/502|https://api.foundries.io/ota/repo/andy-corp//api/v1/user_repo/root.json|KeyserverHttpClient|Unexpected response from remote server at http://tuf-keyserver:9001/api/v1/root/3e16eadb-5ca2-478e-9975-9dd632c12f28|GET|412|There are no private keys for that role
~~~

This particular namespace, andy-corp, has offline keys. So, I find that message confusing. Any ideas? my next step is to look at database dumps of the keyserver to try and piece together what has changed.

**Comment by doanac** [comment]
Here's some more details that might help. I poked around in the DB and it looks like I have 3 root roles  ( I guess this my initial root role, and i think i've rotated my root offline key twice)?:
~~~
select * from signed_root_roles where repo_id = "f10bdff5-1377-435f-92d7-88b24cf09974";
...
3 rows in set (0.004 sec)
~~~

I'm also able to my 3.root.json file (aktualizr-get for the win!):
~~~
# aktualizr-get -u https://ota-lite.foundries.io:8443/repo/3.root.json
   info: Reading config: "/usr/lib/sota/conf.d/30-rollback.toml"
   info: Reading config: "/usr/lib/sota/conf.d/40-hardware-id.toml"
   info: Reading config: "/var/sota/sota.toml"
   info: Reading config: "/etc/sota/conf.d/z-50-fioctl.toml"
   info: Use existing SQL storage: "/var/sota/sql.db"
{"signatures":[{"keyid":"8c7b5300150454746be82c56f5a486853f37e045b21ac8e5d1438cc275b8dd67"
~~~

So it seems like the problem is that aktualizr (as required by Tuf) first checks for an updated root.json by going from its current 3.root.json to 4.root.json. This is normal and done all the time. However, rather than the reposerver sending by a 404, its blowing up with this 424 error.

This makes me think the tufkeyserver thinks I'm supposed to have a 4th root role but I don't? Maybe we have a keyserver bug/issue/something?

I also wonder if aktualizr is doing the right thing here with a failure on root.json. I know just enough about TUF to be dangerous, but - my 3.root.json is good and my targets.json, timestamp.json are signed with keys from it and haven't expired. Things appear kosher, but I guess I'm missing an attack vector?

**Comment by doanac** [comment]
actually - i didn't understand this correctly at all. my root role has expired:
~~~
signed" : {
      "_type" : "Root",
      "consistent_snapshot" : false,
      "expires" : "2020-04-12T21:13:18Z",
~~~

That was the issue. So I was dumb when I rotated my root keys and didn't know.  This leaves me with 2 questions:

1) https://github.com/advancedtelematic/aktualizr/issues/1552#issuecomment-583949004 - i think those steps aren't quite right because they produce a root key that's invalid after 30 days. From my poking around, it looks like 2 years is what you default the initial offline root to.

2) Is there any way to recover from this? I think the answer is "No, you've bricked your deployment". A key rotation would be needed and the server isn't going to trust me signing the new key with my expired key.

**Comment by doanac** [comment]
I can answer question 2 from above now. I was able to rotate root keys. I had to manually edit the unsigned root.json file and then re-sign it, but it worked. The big problem i still have is that my unsigne root.json is good with a sensible expiration. But when I sign it, it gets downgraded to 30 days. I'm going to consult the garage-sign code now and see if there's a way around that.

**Comment by doanac** [comment]
turns out i was using an old garage-sign and this was fixed. sorry for the noise.

**Comment by patrickvacek** [comment]
> turns out i was using an old garage-sign and this was fixed. sorry for the noise.

Ah, sorry for troubles, but I'm glad you got it sorted out! Thanks for letting us know. Do you still have any lingering concerns, or are there things that could be improved in the documentation?

**Comment by doanac** [comment]
It was all self-inflicted. However, I do think there are two use cases that could be covered in this document: https://docs.ota.here.com/ota-client/latest/rotating-signing-keys.html#_rotate_the_online_keys_with_your_new_offline_keys

1) how to rotate a root key (you need to do it at least every 2 years - or at least how to bump the current key's expiration value). This isn't exactly straightforward, as you need to understand how to look at your offline tufrepo stuff and [figure out your root](https://github.com/foundriesio/fioctl/blob/master/subcommands/keys/rotate.go#L48).

2) Adding/Swapping out a targets signing key. I'm about to look into this very topic. I suspect its a slight variation of #1 above.  But its nice to hear this from the experts.

**Comment by patrickvacek** [comment]
@ammaboateng @tkfu @simao this might be some interesting feedback for y'all for how to improve our docs and tooling.
