### ISSUE TITLE
CMake Error, Cannot find source file: build/jsoncpp/jsoncpp.cc

### ISSUE THREAD

**Issue by adlingepa** [advancedtelematic/aktualizr#1657]
[cmake_build.log](https://github.com/advancedtelematic/aktualizr/files/4527340/cmake_build.log)
Cloned the repo. installed all dependencies. started building as per steps. I got error
Attached the complete log file for cmake build
```
CMake Error at CMakeLists.txt:403 (add_library):
  Cannot find source file:

    /home/prashant/work/OTA/Uptane/aktualizr/build/jsoncpp/jsoncpp.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

```

**Comment by patrickvacek** [comment]
That's a file built by one of our dependencies. It looks like it is missing. Does retrying `git submodule update --init --recursive` help?

**Comment by adlingepa** [comment]
Thank you for your response.
Yes I tried, it doesn't helped. 
Then I tried below command from build directory,
Run below command just before cmake
`../third_party/jsoncpp/amalgamate.py -t ../third_party/jsoncpp/ -s jsoncpp/jsoncpp.cc`

Then cmake was successful, but going forward make operation failed with below error,
[ 46%] Built target crypto
[ 46%] Generating sql_schemas.cc, sql_schemas_target
```
/usr/bin/env: ‘python3\r’: No such file or directory
src/libaktualizr/storage/CMakeFiles/storage.dir/build.make:61: recipe for target 'src/libaktualizr/storage/sql_schemas.cc' failed
make[2]: *** [src/libaktualizr/storage/sql_schemas.cc] Error 127
CMakeFiles/Makefile2:13024: recipe for target 'src/libaktualizr/storage/CMakeFiles/storage.dir/all' failed
make[1]: *** [src/libaktualizr/storage/CMakeFiles/storage.dir/all] Error 2
```

I resolved the same with below commands,
```
dos2unix /home/prashant/work/OTA/Uptane/aktualizr/src/libaktualizr/storage/embed_schemas.py
dos2unix: converting file /home/prashant/work/OTA/Uptane/aktualizr/src/libaktualizr/storage/embed_schemas.py to Unix format...
```

Thank you,
Prashant

**Comment by patrickvacek** [comment]
Glad you resolved the line ending problem. I'm not sure how that happened, though; that file is stored in the git repo with Unix line endings, which is what we normally prefer.

Are you still having problems or are you able to build and run successfully now?

**Comment by adlingepa** [comment]
Yes, with above workaround I am able to build and run the application successfully.
Thanks,
Prashant
