### ISSUE TITLE
clang-tidy-6.0 is not supported by debian:testing

### ISSUE THREAD

**Issue by mike-sul** [advancedtelematic/aktualizr#1675]
The test container ./docker/Dockerfile.debian.testing cannot be built anymore; it looks like clang-tidy v6  is not supported on debian:testing (it shows 'bullseye/sid' release for me).

`
mike@msul:~/work/here/projects/aktualizr$ docker build -t aklite-test -f ./docker/Dockerfile.debian.testing .
Sending build context to Docker daemon  160.1MB
Step 1/14 : FROM debian:testing
 ---> c5552d611861
Step 2/14 : LABEL Description="Aktualizr testing dockerfile for Debian Unstable + static checks"
 ---> Using cache
 ---> e9c5da304a85
Step 3/14 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 46ef8e69a95d
Step 4/14 : RUN apt-get update && apt-get -y install --no-install-suggests --no-install-recommends   apt-transport-https   asn1c   autoconf   automake   bison   ccache   clang-6.0   clang-tidy-6.0   clang-tools-6.0   clang-format-6.0   cmake   curl   doxygen   e2fslibs-dev   g++   gcc   git   graphviz   jq   lcov   libarchive-dev   libboost-dev   libboost-log-dev   libboost-program-options-dev   libboost-system-dev   libboost-test-dev   libboost-thread-dev   libcurl4-openssl-dev   libengine-pkcs11-openssl   libexpat1-dev   libfuse-dev   libglib2.0-dev   libgpgme11-dev   libgtest-dev   liblzma-dev   libp11-dev   libsodium-dev   libsqlite3-dev   libssl-dev   libtool   lshw   make   ninja-build   net-tools   opensc   pkg-config   psmisc   python3-dev   python3-gi   python3-openssl   python3-venv   softhsm2   sqlite3   strace   valgrind   wget   xsltproc   zip
 ---> Running in c434a8a23e91
Get:1 http://deb.debian.org/debian testing InRelease [116 kB]
Get:2 http://deb.debian.org/debian testing/main amd64 Packages [7705 kB]
Fetched 7821 kB in 2s (3291 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package clang-tidy-6.0
E: Couldn't find any package by glob 'clang-tidy-6.0'
E: Couldn't find any package by regex 'clang-tidy-6.0'
`

**Comment by patrickvacek** [comment]
This is strange; it still appears to work for our CI. We'll look into it, although we were already trying to upgrade to a newer version of clang-tidy anyway.

**Comment by mike-sul** [comment]
Most likely it works for the CI because it uses the cached images if it's built with '--no-cache' it fails. I just took `aktualizr/docker/Dockerfile.ubuntu.bionic` container and added clang* into it, so it can serve as a container for running the clang-tidy tests.

**Comment by lbonn** [comment]
Fixed for now in #1678. We'll probably want to upgrade to a new version soon though.

**Comment by mike-sul** [comment]
thanks!
