### ISSUE TITLE
Incorrect warning/error messages for Image Repo targets verification

### ISSUE THREAD

**Issue by mike-sul** [advancedtelematic/aktualizr#1692]
@patrickvacek Hey Patrick,  is this error message correct, it says "Image repo Root verification failed: " 
while Image Repo Targets are verified here? https://github.com/advancedtelematic/aktualizr/blob/647f691a9633d86bb8407114039d37013d6bbd8c/src/libaktualizr/uptane/imagerepository.cc#L272

Also, I am not sure if it actually should be an error message taking into account that it is OK  if it fails if Snapshot is updated. The subsequent  logic `if (fetch_targets) {     fetchTargets(storage, fetcher, local_version); }` will do verification of the new Targets and if the verification fails at this stage then it is really an error?

**Comment by patrickvacek** [comment]
>  is this error message correct, it says "Image repo Root verification failed: "
> while Image Repo Targets are verified here?

No, looks like a typo.

> Also, I am not sure if it actually should be an error message taking into account that it is OK if it fails if Snapshot is updated. The subsequent logic `if (fetch_targets) { fetchTargets(storage, fetcher, local_version); }` will do verification of the new Targets and if the verification fails at this stage then it is really an error?

You are completely correct. This is on my list of things to address sooner or later. It's annoying because sometimes it really is an error but usually it is not. It's pretty obvious by what you see next in the logs, but still, I'd like to clean that up.
