### ISSUE TITLE
Build with PKCS#11

### ISSUE THREAD

**Issue by clem844** [advancedtelematic/aktualizr#1699]
Hi,

I am currently trying to setup Aktualizr to leverage PKCS#11 capabilities of a TPM.
Target device: `Raspberry Pi 3`
Aktualizr version: `2020.7-1-g6ff7f4216`

With the build option BUILD_P11 set to ON (CMakeList.txt, line 27)
The configuration file for Aktualizr is:
```
[tls]
server_url_path = "/var/sota/import/gateway.url"
cert_source = "pkcs11"
pkey_source = "pkcs11"

[p11]
module = "/usr/lib/libtpm2_pkcs11.so.0"
pass = "12345"
uptane_key_id = "7"
tls_clientcert_id = "8"
tls_pkey_id = "1"

[uptane]
key_source = "pkcs11"

[import]
base_path = "/var/sota/import"
tls_cacert_path = "root.crt"
```
However, when starting aktualizr, the following error appears: `Aktualizr was built without PKCS#11`
What am I missing here?

**Comment by zabbal** [comment]
Are you sure libp11-3 and libp11-dev are installed on your build machine?

**Comment by clem844** [comment]
They were not. But it doesn't change anything now that I've installed them on the build machine...
