### ISSUE TITLE
void* userdata in rviRegisterService() points to stack

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/aktualizr#176]
When debugging an issue with the RVI mode of aktualizr, I ran into a bug where the rvi callbacks were not working correctly.  I think the problem is with the following piece of code that registers the service callbacks:

https://github.com/advancedtelematic/aktualizr/blob/master/src/sotarviclient.cc#L60

rviRegisterService takes a void* pointer for 'user data', but in this case this pointer is shared among every iteration of the loop, and also on the stack.

One solution might be to split callbackWrapper into one function for each of "notify", "start", "chunk", "finish", "getpackages", "abort", and make userdata a pointer to the SotaRVIClient object.  I'm sure there are nicer solutions too :)

**Comment by patriotyk** [comment]
Ok, I understand the problem, this bug happens after upgrading of rvi_lib, -
 https://github.com/GENIVI/rvi_lib/commit/194ac9f4785de34fc466f6cc6f68fda64260e10f#diff-a6d917e8e3df6ded8aaa00472ea92f6d , now rvi_lib doesn't copy the user_data.
