### ISSUE TITLE
Configuration option to skip some UPTANE checks

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/aktualizr#191]
The current server implementation doesn't support the full UPTANE security model. In order to test Aktualizr against the server that we currently have deployed, we need a configuration option to disable/relax some of the security checks that we perform. There are 3 levels for this configuration flag:

* Full UPTANE checks
* All the UPTANE checks except those relating to rolling-back to an older version (this is to allow demos to switch between 2 versions)
* Compatibility with https://qa-app.atsgarage.com

We will have to do some tests to discover exactly which checks need disabling for the last option, and it should be easy to audit which checks are being skipped.

**Comment by OYTIS** [comment]
@cajun-rat @patriotyk @Danten 
Do we really need the roll-back? As far as I understand, if we issue a downgrade to a previous version, the server should issue a new snapshot with increased version number and the respective timestamp. From point of view of the client it will be an upgrade, not a downgrade anyway.
Correct me if I'm wrong.

**Comment by cajun-rat** [comment]
Yes, the version number from the director can always increase, but the version number in the targets.json from the images repository will go backwards during a rollback (because that number is signed offline)

**Comment by OYTIS** [comment]
@cajun-rat OK, I see, thank you (although I don't quite understand what kind of protection does version check on targets.json give us when we already have snapshot.json).

@patriotyk Then the implementation in https://github.com/advancedtelematic/aktualizr/pull/193 is not quite correct. uptane.allow_downgrade shouldn't let us use outdated timestamp.json, it just should disable version check for targets.json (which is now missing anyway as far as I can see).

@heartsucker Could we add test for targets.json downgrade attempt to uptane-test-vectors?

**Comment by patriotyk** [comment]
@OYTIS  Yeah I see. I will prepare the PR that fixes it.
