### ISSUE TITLE
Set default values of uptane.* URIs to be relative to tls.server

### ISSUE THREAD

**Issue by OYTIS** [advancedtelematic/aktualizr#201]
Currently we're accessing /repo, /director and /treehub through the device gateway only. It would be convenient to set the URI just once insead of copying it to 4 different locations.
That can be achieved by setting uptane.director_server, uptane.repo_server and uptane.ostree_server to tls.server + {"/director", "/repo", "/treehub} by default in config.cc. It's worth to keep it possible to override default values though.

It should be also possible to set tls.server from a file without copying URI to sota.toml, another option like tls.server_uri_file would help us a lot.

**Comment by OYTIS** [comment]
@patriotyk Yes, it sounds like a better solution.

**Comment by cajun-rat** [comment]
Fixed in 7a5d16832fc0905f57cfb0cd3a768b2e5d456d29
