### ISSUE TITLE
Old installed_image is returned when in the installation report manifest

### ISSUE THREAD

**Issue by OYTIS** [advancedtelematic/aktualizr#203]
The director uses "installed_image" section in manifest.json to determine what version is installed, but the client always reboots the image we're currently running in this field. That basically means that the update will be seen as pending in the garage UI until we reboot the device.
I'm not sure what's the right solution here: either the client should send the newly installed image or director/UI should show something different or it can be left as is (the new image isn't really installed until we reboot after all).
Let there be an issue for that anyway.

**Comment by cajun-rat** [comment]
Fixed in df863897af890b2fbbf8c8fd83f9f78eaf59a2d0
