### ISSUE TITLE
Uncaught exception: TargetHashMismatch

### ISSUE THREAD

**Issue by taheris** [advancedtelematic/aktualizr#245]
A thrown `TargetHashMismatch` exception puts the client into an abort crash loop.

**Comment by patriotyk** [comment]
Do You use the latest codebase?

**Comment by taheris** [comment]
I'm using an image built from the latest meta-updater: https://github.com/advancedtelematic/meta-updater/blob/morty/recipes-sota/aktualizr/aktualizr_git.bb#L16

It looks to be a few commits old: `7ca3af4e2f47ca7a3a67866023de3f8a97425991`

**Comment by patriotyk** [comment]
This issue has been fixed in 4628b213f27ff7041067bf4711726fc30375d1ae

**Comment by taheris** [comment]
👍
