### ISSUE TITLE
Support binary target downloads

### ISSUE THREAD

**Issue by taheris** [advancedtelematic/aktualizr#247]
Right now the `UptaneTargetsUpdated` event will always try to install it as an OSTree package. We also want to support binary image downloads, which will download the image from the TUF image repository then send a manifest back to the director to notify it of the successful download.

edit: [JIRA ticket](https://advancedtelematic.atlassian.net/browse/PRO-3450)

**Comment by heartsucker** [comment]
This is also needed to catch a lot of the verification checks in the test vectors. Some are erroneously passing because they never download/check a target.
