### ISSUE TITLE
kernel arguments get duplicated on update

### ISSUE THREAD

**Issue by guyshapiro** [advancedtelematic/aktualizr#309]
On the uboot script, some arguments such as "ostree_root" are appended to the bootargs  from `/boot/loader/uEnv.txt`.
(see for example https://github.com/advancedtelematic/meta-updater-raspberrypi/blob/morty/recipes-bsp/u-boot-otascript/u-boot-otascript/uEnv.txt#L4 )

When deploying an update, Aktualizr reads the content of /proc/cmdline, and adds it to the deployment parameters. This tells OSTree to add those arguments to the uEnv file.
(the code starts here: https://github.com/advancedtelematic/aktualizr/blob/master/src/ostree.cc#L168 )

The result is that each deployment and reboot cycle creates another copy of the arguments.

What is the reason to copy the kernel parameters from "/proc/cmdline"?
Do I miss something?

**Comment by cajun-rat** [comment]
@OYTIS Does #308 fix this?

**Comment by guyshapiro** [comment]
Looks like the same issue as #308.

I believe that the Rust client has the same issue (https://github.com/advancedtelematic/rvi_sota_client/blob/master/sota-client/src/datatype/ostree.rs#L100). The --karg-proc-cmdline argument should probably be removed.

**Comment by cajun-rat** [comment]
Fixed in #308, closing
