### ISSUE TITLE
testing strategy for class servercon

### ISSUE THREAD

**Issue by embmk** [advancedtelematic/aktualizr#38]
If the http connection class managing communication to the sota server will be kept, the way of testing its methods has to be discussed. The current implementation shows two different approaches to substitute parts that rely on communication with the server.
For the oauthtoken-class the methods have been reimplemented to get a valid token when testing/calling parts that rely on a valid token.
For download_update an additional method is implemented and embedded in a hash-define that is activate when building the tests in order to test using a valid available-update-information.

**Comment by cajun-rat** [comment]
We need to support multiple protocols to communicate with the server by February 2017, since we will support GENIVI RVI as well as https.  I suspect that this is a good seam to insert a testing mock too.  I would prefer to avoid using the preprocessor to switch in testing code.
