### ISSUE TITLE
Communicate with RVI Core

### ISSUE THREAD

**Issue by taheris** [advancedtelematic/aktualizr#53]
Using [librvi](https://github.com/genivi/rvi_lib), enable the C++ SOTA client to communicate with RVI.

The Rust client currently implements this by creating an `Edge` server (which is an HTTP server listening at the interface defined at `network.rvi_edge_server`). The Edge server connects to an RVI Client on startup and registers all the available services (`notify`, `start`, `chunk`, `abort`, `finish` and `getpackages`).

When the RVI client notifies the SOTA client of a new update, this will trigger a download in chunks which are then [re-assembled](https://github.com/advancedtelematic/rvi_sota_client/blob/master/src/rvi/transfers.rs#L262) into the final package.

Events are broadcast to the rest of the SOTA system as follows:

- `notify` -> `UpdateAvailable`
- `finish` -> `DownloadComplete`
- `report` (getpackages) -> `InstalledSoftwareNeeded`

Where `librvi` already implements features that were done manually in the Rust client, the `librvi` implementation should be used instead.

Documentation outlining the message formats and communication can be found here:
- http://advancedtelematic.github.io/rvi_sota_server/cli/client-implementation.html
- http://advancedtelematic.github.io/rvi_sota_server/cli/client-implementation-example-session.html

For testing, there is documentation on bringing up the rvi_sota_server with an RVI client and server here: http://advancedtelematic.github.io/rvi_sota_server/doc/deployment-with-dockercompose.html

**Comment by codders** [comment]
Github link https://github.com/GENIVI/rvi_lib/

**Comment by cajun-rat** [comment]
Done
