### ISSUE TITLE
Feature Request: Log progress of ostree pull's

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#670]
I find it a little difficult while looking at aktualizr's debug logs to determine the status of an ostree-pull. Glancing at the code, I think it might be relatively easy to add progress information. I'm not sure I have a good way to set up and test correctly, but here's what I think.

Update the call to [ostree_repo_pull_with_options](https://github.com/advancedtelematic/aktualizr/blob/master/src/ostree.cc#L59) by passing a progress callback. The callback is a little tricky, but I *think* this could be built by first creating a function similar to [ostree_repo_pull_default_console_progress_changed](https://github.com/ostreedev/ostree/blob/master/src/libostree/ostree-repo.c#L4433) that just calls "LOG_INFO" rather than the "glnx_console_text" stuff. Then the progress callback could be constructed with something like:
~~~
 progress = ostree_async_progress_new_and_connect (aktualizr_progress_cb, NULL);
 if (!ostree_repo_pull_with_options(repo.get(), remote, options, progress, cancellable, &error)) ...
~~~

**Comment by doanac** [comment]
I'm not sure if this is possible. However, I think it would be super awesome if this "percent-updated" could somehow find its way into ATS-Garage's device-queue status.

**Comment by patrickvacek** [comment]
@doanac It would probably be difficult to get that level of detail into the Garage, but getting it into the aktualizr logs at least for debugging seems possible. Thanks for looking into it!

**Comment by doanac** [comment]
I was having trouble cross-compiling for my device, but after looking more at the ostree version this builds against, it might be even easier. My totally untested but "it compiles" patch looks like:
~~~
diff --git a/src/ostree.cc b/src/ostree.cc
index feeca1f..c8fc976 100644
--- a/src/ostree.cc
+++ b/src/ostree.cc
@@ -10,10 +10,22 @@
 #include <boost/algorithm/string/classification.hpp>
 #include <boost/algorithm/string/split.hpp>
 #include <boost/filesystem.hpp>
+#include <ostree-1/ostree-async-progress.h>
 
 #include "logging.h"
 #include "utils.h"
 
+static void aktualizr_progress_cb(OstreeAsyncProgress *progress,
+                                  gpointer data __attribute__((unused)))
+{
+  char *status = ostree_async_progress_get_status(progress);
+  if (status) {
+    LOG_INFO << "Pull status: " << status;
+    g_free(status);
+  }
+}
+
+
 data::InstallOutcome OstreeManager::pull(const boost::filesystem::path &sysroot_path, const std::string &ostree_server,
                                          const KeyManager &keys, const std::string &refhash) {
   const char *const commit_ids[] = {refhash.c_str()};
@@ -21,6 +33,7 @@ data::InstallOutcome OstreeManager::pull(const boost::filesystem::path &sysroot_
   GError *error = NULL;
   GVariantBuilder builder;
   GVariant *options;
+  OstreeAsyncProgress *progress;
 
   std::shared_ptr<OstreeSysroot> sysroot = OstreeManager::LoadSysroot(sysroot_path);
   std::shared_ptr<OstreeRepo> repo = LoadRepo(sysroot, &error);
@@ -55,7 +68,8 @@ data::InstallOutcome OstreeManager::pull(const boost::filesystem::path &sysroot_
 
   options = g_variant_builder_end(&builder);
 
-  if (!ostree_repo_pull_with_options(repo.get(), remote, options, NULL, cancellable, &error)) {
+  progress = ostree_async_progress_new_and_connect(aktualizr_progress_cb, NULL);
+  if (!ostree_repo_pull_with_options(repo.get(), remote, options, progress, cancellable, &error)) {
     LOG_ERROR << "Error of pulling image: " << error->message;
     data::InstallOutcome install_outcome(data::INSTALL_FAILED, error->message);
     g_error_free(error);
~~~

**Comment by patrickvacek** [comment]
@doanac It looks like this might work, but when I tried it, I didn't see any additional messages. However, the pull only took 9 seconds, which might not be enough to trigger a callback. I'm not sure how the timing works, but that would be worth looking into. You're going to want to clean up that `progress` object, though, and you may want to call `ostree_async_progress_finish` as well. Feel free to make a PR if you get it working, though!
