### ISSUE TITLE
Feature Proposal: Tracking Device Update Status

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/aktualizr#771]
This is somewhat I spin-off of #670 with some details around what might be possible. My use case might be a bit different than normal ATS Garage usage. However, I find it a bit frightening that I hit "apply update" in the UI and then sit in the dark for some $amount_of_time_that_increases_based_on_the_ostree_delta_size until it finally shows success. With PR #767 we now have a fairly good estimate of how far along the update is. I think it would be a really slick feature to reflect that inside the UI. To help get the conversation started, I thought I'd propose one way I think could work:

## Director Changes

 Add a new text column to `device_update_targets` named "status".
 Add a new admin endpoint:
```
  PUT /api/v1/admin/devices/<deviceUuuid>/queue/<updateUuid>
```
The payloads could look like:
```
    data: {'status': '10%'}
    data: {'status': '13 metadata, 16 content objects fetched; 44683 KiB transferred in 23 seconds'}
    data: {'Performing sync()'}
```
  The director's existing ``queue`` endpoint could include this new attribute in each item

## Aktualizr Changes

Have the ``Repository::downloadTarget`` code pass some type of status callback to ``OstreeManager::pull``. This callback would be responsible for making PUTs on the new director endpoint.

I'm curious about a few things:
1) Your thoughts on the idea?
2) Your willingness to accept such a change into aktualizr and director?
3) If 1 and 2, then how much help from me would you need? ie - is this something I need to do myself, or would you guys be willing to do some amount of the work? I feel fairly comfortable doing the aktualizr changes. My Scala skills are pretty lacking, but I think there's enough code in Director that I could figure out how to copy/paste my way through it.

**Comment by jerrytrieu** [comment]
Yes, we are definitely planning on adding this feature. 

The Director `/api/v1/admin/` endpoints are not accessible to devices - it should be `/api/v1/device/:deviceUuid/download_progress` which the device would access at `/director/download_progress` on the device-gateway. The device should specify the `target` `filepath` it is reporting status for, as it would be downloading multiple images for its primary and secondary ECUs as part of the update (the device doesn't care about the `updateUuid`). There should be some way to configure how often the device should report progress.  The implementation on the Director may need an additional table and `/admin/` endpoint to retrieve this info on the admin-UI. Going forward, the backend should track when each download was started, paused, resumed, or canceled.

Let's groom this feature at our next sprint planning.

**Comment by doanac** [comment]
There's one more thing to consider. This is probably more device-registry specific, so let me know if you think its orthogonal to this and should be its own bug. My understanding of secondary ECU's is quite limited, so what I'm saying might be a little too primary-ecu centric:

We often have confusion about the true status of an update. OTA+ just knows what's been applied. However, the image isn't active until the device reboots. In "ostree admin status" terms, there's the "active" image and the "pending" image. I haven't quite wrapped my mind around how this would get modeled,  but I think its important to reflect this state. 

Anyway - let me know if you guys need any help with this.

**Comment by cajun-rat** [comment]
The status of an update is something that I think we should try and model in the system a bit more thoroughly. The difference between 'what is running now' and 'what will be running on the next reboot' is an important distinction, certainly. Last week we were talking about how interactions with a boot watchdog will work, and this adds a new type of failure: it is possible for an update to download and apply OK, but get reverted by the watchdog.

One possibility would be to have a 'point of no return' for the installation of an update, therefore the state machine would look like:

1. Installing
2. Installed, waiting for a reboot to start running the software.
3. Running, waiting the boot watchdog to be happy
4. Installed (at this point the installation can't 'fail')

If the point of no return was defined as 'can communicate with the update server', then states 2 and 3 could be merged, but this limits the design of the boot watchdog, and we may not be able to dictate that.

Another approach would be to assume that a revert can happen at any time, but this means that 'green' devices can suddenly turn 'red' in the UI, and means that installation is never really 'successful', only that it hasn't failed yet:

1. Installing
2. Installed, waiting for a reboot to start running the software.
3. **Installed** (most devices stop here)
4. Installation rolled back (possibly)

**Comment by doanac** [comment]
Thanks for bringing up the watchdog scenario. @rsalveti will eventually be looking at that for us and I've had a hard time seeing how it would fit into things. My initial feeling is that your second approach makes more sense for my needs.

**Comment by rsalveti** [comment]
Related to the update state machine, do you guys have any plans to manage automatic reboots as part of the update process as well?

I was wondering if OTA+ could also have the action to trigger a reboot once the update is applied (e.g. critical update in place, with the need to reboot all the managed devices).

Besides the automatic reboot, it would also be nice to have a way to create an additional systemd service that could watch for a file/flag and proceed with an update based on a time schedule set by the user.

**Comment by cajun-rat** [comment]
FYI there is now support for a boot watchdog, at least on R-Pi + U-Boot https://github.com/advancedtelematic/meta-updater-raspberrypi/pull/21/files

Automatic reboots are certainly something that we would like to handle. We've talked about it a bit, but I don't think anyone has a concrete plan for how it should work yet.

Firstly, there is the question of where we signal that an automatic reboot should be performed. This could either be in the update itself, or it could be a property of the deployed system. Putting it in the update gives some more flexibility, but logic in the update metadata means that the admin deploying the update could easily forget to check a box and mess up the deployment.

It would also be nice to schedule a reboot at a convenient time (e.g. overnight for IoT devices, or when the system has been 'idle' for a while.

Separately to policy, there is also the mechanism to consider.  For the automotive use case the reboot process is likely to be more complex than kicking systemd, so we'd need some way to let users to plug in their own reboot mechanism.

I don't think we need to solve all those problems at once, but it would be nice to has a design that would support those cases eventually.

**Comment by rsalveti** [comment]
> Firstly, there is the question of where we signal that an automatic reboot should be performed. This could either be in the update itself, or it could be a property of the deployed system. Putting it in the update gives some more flexibility, but logic in the update metadata means that the admin deploying the update could easily forget to check a box and mess up the deployment.

I believe that being a property of the deployed system could be a good initial implementation, as the user could then define the reboot policy when deploying the device (could also be configured as part of the image itself).

> It would also be nice to schedule a reboot at a convenient time (e.g. overnight for IoT devices, or when the system has been 'idle' for a while.

At least rebooting at an specific time would not be so hard to implement (systemd could receive the event and the user could configure another job to reboot at an specific time), but a smarter logic (e.g. idle) would need more thinking.

> Separately to policy, there is also the mechanism to consider. For the automotive use case the reboot process is likely to be more complex than kicking systemd, so we'd need some way to let users to plug in their own reboot mechanism.

+1, for cloud or cluster-based solutions this would also be required, as it needs to coordinate the reboot process with other clients. The implementation would need to support external plugins I would imagine.

**Comment by patrickvacek** [comment]
@lbonn This conversation might be relevant for what you are working on at the moment.

**Comment by lbonn** [comment]
Yes that's something we've been working on for about a month or two. The initial client part is already merged. See current events here, still subject to change: https://github.com/advancedtelematic/aktualizr/blob/master/src/libaktualizr/primary/reportqueue.h.

However, it's not visible on the production SaaS yet. Hopefully, this will come soon enough.

**Comment by doanac** [comment]
I think this largely completed now. There's some minor stuff like %downloaded that could be nice, but everything is in place now to make that happen.
