### ISSUE TITLE
Signed by unknown keyid is now fatal after #879

### ISSUE THREAD

**Issue by rsalveti** [advancedtelematic/aktualizr#899]
As covered by @doanac at #783, we're using aktualizr / ota+ after doing a key rotation as described at https://docs.atsgarage.com/prod/rotating-signing-keys.html.

Before #879 the message we were getting was simply "Signed by unknown keyid", without aborting the execution. With that merge request the warning is now fatal as it is throwing BadKeyId, making it unable to fetch and download newer images.

As that merge request was created to fix the vector tests (and ended up changing a core behavior), it looks like a possible regression to me, but I'm not able to confirm as I'm not so familiar with the aktualizr codebase.

Can someone take a look and see if this is indeed the expected behavior here? Thanks!

**Comment by rsalveti** [comment]
@patrickvacek mind having a look?

**Comment by patrickvacek** [comment]
@rsalveti I've confirmed that the current behavior is wrong and the old behavior should be maintained. I'm looking into a fix now.

**Comment by patrickvacek** [comment]
See https://github.com/advancedtelematic/aktualizr/pull/900 for a potential fix.

**Comment by patrickvacek** [comment]
Closing the issue as it is now reported fixed.
