### ISSUE TITLE
aktualizr release tarballs do not include sub modules

### ISSUE THREAD

**Issue by agners** [advancedtelematic/aktualizr#959]
The sub modules are missing in the release tarball. This does not allow to build from release tarballs...

**Comment by agners** [comment]
Besides the current issue with gitsm, we used to have race conditions before when running bitbake instances in parallel with shared DL_DIR. Maybe they are resolved with the latest changes, we will see.

Anyway, using tarballs would sidestep the whole issue and also lead to smaller download size.

It also just seems a bit pointless providing a release tarball which can't be properly built. I guess the deb files get built on a custom build system anyway? So creating a proper release tarball should be possible there?

**Comment by patrickvacek** [comment]
>  used to have race conditions before when running bitbake instances in parallel with shared DL_DIR.

Interesting. We generally don't do that ourselves, but do you only have problems with meta-updater/aktualizr, or does that also happen to other layers/recipes? It could indeed be related to the submodule issue.

> using tarballs would sidestep the whole issue and also lead to smaller download size.

While that is true, we currently update the aktualizr recipe in meta-updater far more often than we issue releases on github. We are considering changing that process a bit, but especially for the master branch of meta-updater, it is likely to occasionally be ahead of the last github release.

> I guess the deb files get built on a custom build system anyway? So creating a proper release tarball should be possible there?

Yes, that is true, and that is what we've looked into. So far, there hasn't been a need for it, and now we are in the midst of considering a change in CI, so if there isn't an urgent need, we might want to wait on that.

**Comment by agners** [comment]
> > we used to have race conditions before when running bitbake instances in parallel with shared DL_DIR.
> 
> Interesting. We generally don't do that ourselves, but do you only have problems with meta-updater/aktualizr, or does that also happen to other layers/recipes? It could indeed be related to the submodule issue.

In one of our builds it was quite reproducible, seen it in three builds in a row. So far only with aktualizr, but afaict we only use gitsm with ostree and aktualizr.

> 
> > using tarballs would sidestep the whole issue and also lead to smaller download size.
> 
> While that is true, we currently update the aktualizr recipe in meta-updater far more often than we issue releases on github. We are considering changing that process a bit, but especially for the master branch of meta-updater, it is likely to occasionally be ahead of the last github release.
> 
> > I guess the deb files get built on a custom build system anyway? So creating a proper release tarball should be possible there?
> 
> Yes, that is true, and that is what we've looked into. So far, there hasn't been a need for it, and now we are in the midst of considering a change in CI, so if there isn't an urgent need, we might want to wait on that.

That is fine for us, its not an urgent need. We can work around by building the images with separate DL_DIR for now. I was just thinking it would be the right thing to do sometime in the future.
