### ISSUE TITLE
Provisioning docs are outdated

### ISSUE THREAD

**Issue by Bubu** [advancedtelematic/aktualizr#974]
https://github.com/advancedtelematic/aktualizr/blob/master/docs/implicit-provisioning.adoc seems to be outdated.

1) It has a link to https://github.com/advancedtelematic/aktualizr/blob/master/config/sota_implicit_prov.toml which gives `404`
2) The `aktualizr-implicit-prov` method seems to have been removed from the meta-updater repository.

**Comment by Bubu** [comment]
The docs here are outdated as well:https://github.com/advancedtelematic/meta-updater#sota-related-variables-in-localconf

**Comment by patrickvacek** [comment]
@Bubu what did you notice was wrong with the README in meta-updater?

**Comment by Bubu** [comment]
> @Bubu what did you notice was wrong with the README in meta-updater?

Can't find it now. I probably misread something yesterday.

**Comment by patrickvacek** [comment]
Fixed by https://github.com/advancedtelematic/aktualizr/pull/979. Feel free to reopen or open a new issue if you find something is still missing or wrong. Thanks again for pointing out the problem.
